name: Test linux job
on:
  push

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set_var
        run: |
          content=`cat ./test_run.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "resultsJson=$content" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ fromJson(outputs.resultsJson).totalTests }}"